### ISSUE TITLE
global-lentic-mode fails

### ISSUE THREAD

**Issue by marcowahl** [phillord/lentic#10]
Hi Phil,

With the latest melpa package global-lentic-mode fails for me.  Error: some f-xxx function is missing.

A (require 'f) in lentic-doc.el fixes the failure.  But I don't know if this is an appropriate fix.

Best regards,  Marco

**Comment by phillord** [comment]
Thanks. Found that out myself yesterday. I don't know why I didn't occur during my testing.

I'll push a fix out.

**Comment by marcowahl** [comment]
Thanks!
