### ISSUE TITLE
lentic can't work with other SRC block

### ISSUE THREAD

**Issue by tumashu** [phillord/lentic#12]
```
;; * Title
    
;; #+BEGIN_SRC org
This is a test
;; #+END_SRC

;; #+BEGIN_SRC elisp
(message "helloworld")
;; #+END_SRC

;; #+BEGIN_SRC emacs-lisp
(message "test")
;; #+END_SRC

;; # Local Variables:
;; # lentic-init: lentic-orgel-org-init
;; # End:

```

**Comment by phillord** [comment]
It can work with any SRC block but it will need configuring. It does need updating for elisp as that is a standard option for org mode. But for BEGIN_SRC org -- it's not clear what behaviour you would want in this case.

At the current time, though, lentic-org can't cope with two different types of src tag in the same file anyway. It's fixable using the same technique as lentic-asciidoc.

**Comment by tumashu** [comment]
At the current time, though, lentic-org can't cope with two different types of 
      src tag in the same file   anyway. It's fixable using the same technique as lentic-asciidoc.

This is the problem I want to mention，I hope it is addressed as quickly as possible

**Comment by phillord** [comment]
Which is your main problem? You want to use elisp as well as emacs-lisp. Or you want to include many different src blocks?

**Comment by tumashu** [comment]
include different src blocks

**Comment by phillord** [comment]
tumashu <notifications@github.com> writes:

> include different src blocks


Okay. I will add this, probably the version after next.
