### ISSUE TITLE
README too simple for user

### ISSUE THREAD

**Issue by tumashu** [phillord/lentic#16]
README is too simple and nearly useless for end user, In my opinion,  helm's README is a good example: 

https://github.com/emacs-helm/helm/blob/master/README.md

**Comment by phillord** [comment]
I would agree that the documentation is lacking at the moment, but I think that the in package documentation is the way to go. The README.md could do with a little more on how to install, but I was not planning on adding more than that.

**Comment by tumashu** [comment]
I think it should include:
1. description
2. how to install + example
3. how to simple configure + example

**Comment by tumashu** [comment]
I think it should include:
1. description
2. how to install + example
3. how to simple configure + example

**Comment by phillord** [comment]
I'll add the install docs. The rest of the documentation is hyperlinked.

**Comment by tumashu** [comment]
ok, i suggest add example, which is more useful than words.

**Comment by phillord** [comment]
Going to close this now, as I have substantially improved the documentation. Please feel free to re-open if you think that the are further issues.
