### ISSUE TITLE
`lentic-orgel-org-init' conflict with org tags

### ISSUE THREAD

**Issue by tumashu** [phillord/lentic#19]
When I edit head with tags in org buffer, emacs-lisp buffer get wrong result

**Comment by tumashu** [comment]
```
;;; Commentary:
;; * README 								  :README:
;; This is a readme

;;; code:
;; * code                                                                 :Code:
;; #+BEGIN_SRC emacs-lisp
(message "Hello World")
;; #+END_SRC
;; # Local Variables:
;; # lentic-init: lentic-orgel-org-init
;; # End:
```

**Comment by tumashu** [comment]
```
;;; Commentary:
;; * README 								  :README:
;; This is a readme

;;; code:
;; * code                                                                 :Code:
;; #+BEGIN_SRC emacs-lisp
(message "Hello World")
;; #+END_SRC
;; # Local Variables:
;; # lentic-init: lentic-orgel-org-init
;; # End:
```

**Comment by tumashu** [comment]
I only export head with tags :README:. or  :Code:

**Comment by phillord** [comment]
Try this instead.


    ;;; Commentary:
    ;; ** README
    ;; This is a readme
    
    ;;; code:
    ;; ** code
    ;; #+BEGIN_SRC emacs-lisp
    (message "Hello World")
    ;; #+END_SRC
    ;; # Local Variables:
    ;; # lentic-init: lentic-orgel-org-init
    ;; # End:


`* code` is not syntax for the orgel transformation. The
`;;; Commentary;` markers get transformed into Header-1.

**Comment by tumashu** [comment]
;;; Head:

The problem is that it can't add tags which is an important org feature, 

What about ignore transform Head-1 which have tags?  for example:
;; * head1    :tag1:tag2:

**Comment by phillord** [comment]
Yes I agree. This is on my list of things to do!
