### ISSUE TITLE
melpa package warn and error

### ISSUE THREAD

**Issue by tumashu** [phillord/lentic#21]
···
build.el:8:1:Error: Cannot open load file: no such file or directory, commander
...

lentic-asciidoc.el:166:1:Warning: the following functions might not be defined at runtime:
    lentic-commented-asciidoc-configuration,
    lentic-uncommented-asciidoc-configuration
...
lentic-block.el:290:1:Warning: Unused lexical argument `e'
lentic-block.el:401:1:Warning: Unused lexical argument `e'

...
In lentic-dev-enable-insertion-marking:
lentic-dev.el:171:11:Warning: assignment to free variable
    `lentic-enable-insertion-marking'

...
lentic-dev.el:178:1:Warning: the following functions are not known to be defined:
    lentic-mode-after-save-hook, lentic-mode-buffer-list-update-hook

...
lentic-doc.el:85:1:Warning: Unused lexical variable `org-export-htmlize-generate-css'

···

**Comment by phillord** [comment]
Thanks! A fix for the error is in place (that file shouldn't have been included anyway!).

https://github.com/milkypostman/melpa/pull/2533

The byte compile errors are harmless. I'll fix them when I have time!
