### ISSUE TITLE
Error invalid-slot-name during Lentic > Create all 

### ISSUE THREAD

**Issue by darabi** [phillord/lentic#35]
On current master, when I open lentic.el, accept the dir-local variables, and select the menu ```Edit > Lentic > Create All```, I get:

```

Debugger entered--Lisp error: (invalid-slot-name "#<lentic-orgel-to-org-configuration lb-orgel-to-org>" :lentic-file)
  signal(invalid-slot-name ("#<lentic-orgel-to-org-configuration lb-orgel-to-org>" :lentic-file))
  #[(object slot-name operation &optional new-value) "\302\303\304!\"\207" [object slot-name signal invalid-slot-name eieio-object-name] 4 "Method invoked when an attempt to access a slot in OBJECT fails.\nSLOT-NAME is the name of the failed slot, OPERATION is the type of access\nthat was requested, and optional NEW-VALUE is the value that was desired\nto be set.\n\nThis method is called from `oref', `oset', and other functions which\ndirectly reference slots in EIEIO objects."]([object lentic-orgel-to-org-configuration "lb-orgel-to-org" unbound unbound t nil nil nil normal-mode unbound unbound unbound :default t] :lentic-file oset "~/testfile.org")
  apply(#[(object slot-name operation &optional new-value) "\302\303\304D\"\207" [object slot-name signal invalid-slot-name eieio-object-name] 4 "Method invoked when an attempt to access a slot in OBJECT fails.\nSLOT-NAME is the name of the failed slot, OPERATION is the type of access\nthat was requested, and optional NEW-VALUE is the value that was desired\nto be set.\n\nThis method is called from `oref', `oset', and other functions which\ndirectly reference slots in EIEIO objects."] ([object lentic-orgel-to-org-configuration "lb-orgel-to-org" unbound unbound t nil nil nil normal-mode unbound unbound unbound :default t] :lentic-file oset "~/testfile.org"))
  slot-missing([object lentic-orgel-to-org-configuration "lb-orgel-to-org" unbound unbound t nil nil nil normal-mode unbound unbound unbound :default t] :lentic-file oset "~/testfile.org")
  #[(obj slots) "\304\216\305H\n\2057
```

I'm using ```GNU Emacs 24.4.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.8)```.

Thank you

Kambiz

**Comment by phillord** [comment]
What is your test file? And what does the dir-local.el look like?

Can you also try to open "orgel-org.el" from the examples directory, and do the same "Create All". And, finally, open can you try the release version?

Sorry for all the questions -- no idea where this error is coming from off-hand, so I need to be able to reproduce it.

**Comment by darabi** [comment]
As I wrote, my test file was

```
lentic.el
```
which implicates that this .dir-locals.el 
I just tried again with ```orgel-org.el```, and see the same error.

I checked out tag v0.9, which works, so it doesn't seem to be related to my local libraries etc.
The only places in the diff between v0.9 and HEAD where lentic-file shows up, is near some renamed ```lentic-unmatched-commented-block-configuration``` which was renamed to ```lentic-unmatched-commented-chunk-configuration```.

**Comment by darabi** [comment]
I removed lentic, checked out anew and now I cannot reproduce the error any more.

I don't know exactly what went wrong. Sorry for stealing your time.

**Comment by phillord** [comment]
No worries, probably an out-of-date .elc file I would think.
