### ISSUE TITLE
Top Level Heading with Blank

### ISSUE THREAD

**Issue by marcowahl** [phillord/lentic#37]
Hi Phil,

Looks like there shall not be a blank in a top level heading for lentic org/el.

'* Foo Bar' (in org) gets ';;; Foo: Bar:' (in el).  Then in the next lentic session the former org top level heading '* Foo Bar' gets transformed to ';;; Foo: Bar:' and this breaks the structure of the org representation.

Is it somehow possible to use blanks in top level items with org/el?

Thanks,  Marco

PS: Thanks again for lentic!  BTW I use lentic for my init.el now: https://github.com/marcowahl/.emacs.d

**Comment by phillord** [comment]
Yes, I think that this is a limitation at the moment. I had quite a few problems getting this to work consistently. It would a lot easier iff I dropped support for `:tags:` but I had people asking for that also.

I realise that it's different for a .emacs, but mostly .el files use the standard (one word) headers anyway.

I am happy to see your .emacs.d, that's very cool. Ironically, I haven't converted mine yet!

**Comment by marcowahl** [comment]
Thanks for the clarification.  Best regards!
