### ISSUE TITLE
lentic-autoload initialization fails

### ISSUE THREAD

**Issue by marcowahl** [phillord/lentic#4]
Hi Phil Lord,

Thanks for lentic!  I think lentic is a great idea.  Actually I start using it.  Thanks for sharing.

To the issue:
I tried to follow the advise in lentic.el to use

(require 'lentic-autoload)

But without success.  BTW I could not find the respective 'provide'.

Please have a look.

Best regards,  Marco

**Comment by phillord** [comment]
Oh dear. Documentation error, perhaps ironically. Can you try

(require 'lentic-autoloads)

with an "s" please?

Phil

Marco Wahl <notifications@github.com> writes:

> Hi Phil Lord,
>
> Thanks for lentic!  I think lentic is a great idea.  Actually I start using it.  Thanks for sharing.
>
> To the issue:
> I tried to follow the advise in lentic.el to use
>
> (require 'lentic-autoload)
>
> But without success.  BTW I could not find the respective 'provide'.
>
> Please have a look.
>
>
> Best regards,  Marco
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/phillord/lentic/issues/4

-- 
Phillip Lord,                           Phone: +44 (0) 191 208 7827
Lecturer in Bioinformatics,             Email: phillip.lord@newcastle.ac.uk
School of Computing Science,            http://homepages.cs.ncl.ac.uk/phillip.lord
Room 914 Claremont Tower,               skype: russet_apples
Newcastle University,                   twitter: phillord
NE1 7RU

**Comment by marcowahl** [comment]
(require 'lentic-autoloads) is it!

I must have been blind.  Now I see the respective provide.

But please note that I have another issues now.  After triggering a lentic-split there is:

Buffer *Messages*: lentic-mode-split-window-below: Symbol's function definition is void: lentic-ensure-init

And after evaluation of lentic.el:lentic-ensure-init there is

if: Symbol's value as variable is void: lentic-config

Then I evaluated the whole lentic.el and no further issue appeared.


Thanks,  Marco

**Comment by phillord** [comment]
Marco Wahl <notifications@github.com> writes:

> (require 'lentic-autoloads) is it!
>
> I must have been blind.  Now I see the respective provide.

Good stuff!



> But please note that I have another issues now.  After triggering a lentic-split there is:
>
> Buffer *Messages*: lentic-mode-split-window-below: Symbol's function
> definition is void: lentic-ensure-init
>
> And after evaluation of lentic.el:lentic-ensure-init there is
>
> if: Symbol's value as variable is void: lentic-config
>
> Then I evaluated the whole lentic.el and no further issue appeared.


Would you stick this in a new issue for me?

Phil
