### ISSUE TITLE
Performance issue when lentic is loaded

### ISSUE THREAD

**Issue by lionel-** [phillord/lentic#42]
Hello,

I noticed a considerable slow down of my Emacs after inadvertently running a lentic command. Turns out it was because of this hooked command:

```list
(add-hook 'buffer-list-update-hook
          'lentic-mode-buffer-list-update-hook)
```

The slow down occurs on window switching and elscreen tab switching. I find it problematic that it happens even when lentic is not running, just merely loaded.

**Edit**: Actually the slowdown is so noticeable that it would be problematic even when if it only happened while lentic is running.

**Comment by phillord** [comment]
Yeah, it's not good. That hook always was too expensive. I'll have to
find a better way.

I'll remove the hook for now and think of a better way.

Thanks for taking the time to report the bug.
