### ISSUE TITLE
Need package `m-buffer-0.13', but only 0.12 is available?

### ISSUE THREAD

**Issue by dmich2** [phillord/lentic#43]
emacs 24.5
stable.melpa.org
I tried to install lentic but got the following error:
```package-compute-transaction: Need package `m-buffer-0.13', but only 0.12 is available```

**Comment by phillord** [comment]
Oops. I'll release a new version on m-buffer in the next few days.

**Comment by phillord** [comment]
This appears to be fixed now. Thanks for reporting!
