### ISSUE TITLE
Instructions for legacy code don't work on .emacs

### ISSUE THREAD

**Issue by WorldsEndless** [phillord/lentic#46]
To get started with Lentic (emacs 24.4, from the repo)  I've tried to follow the instructions at 

https://github.com/phillord/lentic/blob/master/lenticular.org#converting-legacy-source

However, it didn't work, although the example with lentic.el did. First, I followed the directions to add comented syntax. Then I created a `.dir-local.el` and it didn't seem to do anything at all. Then, I instead copied the `.dir-locals.el` from the source directory and at least now it would properly `C-c , c` and `C-c , b` but the resulting buffer, though it's called emacs.org, is still in emacs lisp mode. Does this have to do with the fact that the base file is ".emacs" and not a .el file? And possibly that the file begins with 

    ; -*-emacs-lisp-*-

? For the .emacs file, I'm guessing there are some natural configs that I'm missing. 

**MORE DETAILS**
Okay, added details needed for the resolution: 
- my .emacs is a symlink to a folder monitored by my ownCloud so I can sink to multiple computers.

**Comment by WorldsEndless** [comment]
**FIXED**

With my setup, I had to make the following changes:
- use .emacs.el rather than .emacs, and then strip out the mode-mandate from the first line of the file (remove `; -*-emacs-lisp-*-`).
- Since .emacs.el is sym-linked to my home dir, I also need to symlink `.dir-locals.el` to the same place.

**Comment by phillord** [comment]
I would use the `lentic-el-org-init` in preference to `lentic-orgel-org-init` -- the latter is designed for Emacs lisp packages. You don't really need things like the first line transformation, nor the special treatment of top level headers in a .emacs file. The el-org transformation is much simpler (and therefore more robust).

I'll add something to the manual.
