### ISSUE TITLE
The lentic split fails

### ISSUE THREAD

**Issue by marcowahl** [phillord/lentic#5]
Hello Phil,

I'm blind again |-(.  No sign of 'provide' in lentic-autoloads.el.  I do not fully grok, but i checked the info about autoloads.  Quote (info:Packaging Basics):

These autoload definitions are saved to a file named ‘NAME-autoloads.el’ in the content directory.
...
After installation, the installed package is "loaded": Emacs adds the
package’s content directory to ‘load-path’, and evaluates the autoload
definitions in ‘NAME-autoloads.el’.

So I think the line (require 'lentic-autoloads) is gratuitous.

Now to the issue of the title.

1. Start Emacs with the line
(global-lentic-start-mode)
in dot.emacs.

2. Load file lentic-org.el from the package directory.

3. Press C-c , b to split in the lentic sense.

Expectation: A further buffer comes to existence.

Observation: The message 'lentic-mode-split-window-below: Symbol's function definition is void: lentic-ensure-init' appears in the mode-line.

BTW: After evaluating buffer lentic.el the split shows the expected behavior.

Best regards,  Marco

**Comment by phillord** [comment]
Okay, easy to fix. The problem is I don't install lentic with package.el, so I miss these things sometime!
